### ISSUE TITLE
Failed to activate the autocomplete-java package

### ISSUE THREAD

**Issue by Pooksoft** [keskiju/autocomplete-java#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [autocomplete-java](https://github.com/keskiju/autocomplete-java) package, v0.5.0
### Stack Trace

Failed to activate the autocomplete-java package

```
At fs is not defined

ReferenceError: fs is not defined
    at /Users/pooksoftdeveloper/.atom/packages/autocomplete-java/lib/AtomAutocompletePackage.js:90:22
    at Array.find (native)
    at AtomAutocompletePackage._getProjectRootDir (/Users/pooksoftdeveloper/.atom/packages/autocomplete-java/lib/AtomAutocompletePackage.js:89:8)
    at AtomAutocompletePackage._refresh (/Users/pooksoftdeveloper/.atom/packages/autocomplete-java/lib/AtomAutocompletePackage.js:54:24)
    at AtomAutocompletePackage.activate (/Users/pooksoftdeveloper/.atom/packages/autocomplete-java/lib/AtomAutocompletePackage.js:35:10)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/package.js:786:28
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/package-manager.js:533:41)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:181:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.reloadGrammar (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:192:21)
    at new TokenizedBuffer (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:78:12)
    at new DisplayBuffer (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:91:32)
    at new TextEditor (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/text-editor.js:121:30)
    at Workspace.module.exports.Workspace.buildTextEditor (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/workspace.js:572:14)
    at /opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/workspace.js:552:24
    at process._tickCallback (node.js:368:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-java, v0.5.0

# Dev
No dev packages
```

**Comment by keskiju** [comment]
I fixed this. Please update and try if it works.
