### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by HlubyLuk** [keskiju/autocomplete-java#20]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-java](https://github.com/keskiju/autocomplete-java) package, v0.9.4
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'match' of undefined
    at AtomAutocompletePackage._onSave (/Users/HlubyLuk/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:120:39)
    at /Users/HlubyLuk/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:53:14
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1038:20)
    at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:594:26)
    at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:558:16)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:542:21)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:633:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:04.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -1:04.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:56.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:49.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:49 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:34.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  4x -0:32.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  3x -0:30.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -0:24.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:21.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:20.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:17.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "java-generator",
      "java-importer"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.19
autocomplete-java, v0.9.4
autocomplete-python, v1.2.4
linter, v1.11.3
linter-javac, v1.4.0
pretty-json, v0.4.1
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by keskiju** [comment]
Caused by a new file that has yet no name. Published a quick fix.
