### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

### ISSUE THREAD

**Issue by Masson** [keskiju/autocomplete-java#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11
**Thrown From**: [autocomplete-java](https://github.com/keskiju/autocomplete-java) package, v0.10.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /Users/masson/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:185:29
    at Array.find (native)
    at AtomAutocompletePackage._getProjectRootDir (/Users/masson/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:184:10)
    at AtomAutocompletePackage._refresh (/Users/masson/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:94:26)
    at /Users/masson/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:69:12
```
### Commands

```
     -0:54.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 open-recent:open-recent-file-1 (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-dot",
      "graphviz-preview",
      "plantuml-preview",
      "tree-view",
      "todo-manager"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-java, v0.10.1
autocomplete-paths, v1.0.2
bottom-dock, v0.3.7
hyperclick, v0.0.35
language-plantuml, v0.2.0
minimap, v4.19.0
open-recent, v4.0.1
plantuml-viewer, v0.7.0
pretty-json, v0.4.1
project-manager, v2.6.5
tool-bar, v0.1.10

# Dev
No dev packages
```

**Comment by keskiju** [comment]
could not reproduce but hopefully this works in the latest version
