### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by Scythe14** [keskiju/autocomplete-java#38]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [autocomplete-java](https://github.com/keskiju/autocomplete-java) package, v1.2.4
### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Users/bouca-_d/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:77

TypeError: Cannot read property 'add' of null
    at /Users/bouca-_d/.atom/packages/autocomplete-java/lib/atomAutocompletePackage.js:77:25
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:312:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:377:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:388:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:366:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:97:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:306:27)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:125:26)
    at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:144:13)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:216:19)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:895:23)
    at Pane.module.exports.Pane.splitDown (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:864:19)
    at atom-pane.commandRegistry.add.pane:split-down-and-copy-active-item (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:257:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```
### Commands

```
     -3:01.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.4.0 core:save (atom-text-editor.editor.is-focused)
  6x -2:40.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:28.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:45.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:42.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:41.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:37.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:36.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:35.8.0 core:cut (atom-text-editor.editor.is-focused)
  2x -1:30.8.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:28.3.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:58.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:51.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.4.0 pane:split-up-and-copy-active-item (atom-text-editor.editor.is-focused)
     -0:00.7.0 pane:split-down-and-copy-active-item (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.19
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
bootstrap-3-snippetset, v0.0.6
file-icons, v1.7.10
jQuery, v1.2.4
java-importer, v1.4.1
language-java, v0.18.0
language-velocity, v0.1.2

# Dev
No dev packages
```

**Comment by keskiju** [comment]
Should work now
